// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orchidea.Data.Context;

namespace Orchidea.Data.Migrations
{
    [DbContext(typeof(OrchideaContext))]
    partial class OrchideaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Orchidea.Data.Models.Flower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d38549a-4e17-4715-ba8b-375db5282666"),
                            Name = "Orchidea"
                        },
                        new
                        {
                            Id = new Guid("7dab7074-d639-4e5f-9385-dedb291e6b27"),
                            Name = "Rose"
                        },
                        new
                        {
                            Id = new Guid("f8b55404-dd8f-4258-b926-58f418fea742"),
                            Name = "Snowdrop"
                        },
                        new
                        {
                            Id = new Guid("013287fb-cabe-4eca-bb27-558e2ae8a294"),
                            Name = "Bluebell"
                        },
                        new
                        {
                            Id = new Guid("cff9330e-9e2e-42e1-9762-9f82940cdc24"),
                            Name = "Daffodil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
